bulk_server: async Namespace Reference
async Namespace Reference
Classes
struct Context
Typedefs
using handle_t = void *
Functions
handle_t connect (std::size_t bulk)
void receive (handle_t handle, const char *data, std::size_t size)
void disconnect (handle_t handle)
Typedef Documentation
handle_t
using async::handle_t = typedef void *
Definition at line 7 of file async.h.
Function Documentation
connect()
handle_t async::connect (std::size_t bulk)
Definition at line 16 of file async.cpp.
{
        auto receiver = std::make_shared<Receiver>();
        auto controller = std::make_unique<Controller>(bulk, receiver);
        auto context = new Context{std::move(controller), {}, {}, {}};
        return reinterpret_cast<void *>(context);
    }
Referenced by AsyncSender::AsyncSender(), and AsyncSender::reconnect().
disconnect()
void async::disconnect (handle_t handle)
Definition at line 54 of file async.cpp.
{
        auto context = reinterpret_cast<Context*>(handle);
        for (const auto& future : context->futures) {
            future.wait();
        }
        context->controller->parse_command("EOF");
        delete context;
    }
Referenced by AsyncSender::reconnect(), and AsyncSender::~AsyncSender().
receive()
void async::receive (handle_t handle, const char * data, std::size_t size)
Definition at line 23 of file async.cpp.
{
        auto context = reinterpret_cast<Context*>(handle);
        auto worker = [](Context* context, const char *data, std::size_t size) {
            std::string line;
            for (std::size_t i = 0; i < size; ++i) {
                if (data[i] != ' ' && data[i] != '\n') {
                    line += data[i];
                } else {
                    if (!line.empty()) {
                        std::lock_guard<std::mutex> lock(context->parser_mutex);
                        context->controller->parse_command(line);
                        line.clear();
                    }
                }
            }
            if (!line.empty()) {
                std::lock_guard<std::mutex> lock(context->parser_mutex);
                context->controller->parse_command(line);
            }
            delete[] data;
        };
        char* data_copy = new char[size];
        memcpy(data_copy, data, size);
        auto future = std::async(std::launch::async, worker, context, data_copy, size);
        std::lock_guard<std::mutex> lock(context->futures_mutex);
        context->futures.push_back(std::move(future));
    }
Referenced by AsyncSender::send().